version: "3.3"

services:
  traefik:
    image: "traefik:v2.3.0"
    command:
      - --entrypoints.web.address=:80
      - --providers.docker
      - --api.insecure
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mshowto:
    image: hellonode:latest
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.mshowto.rule=Host(`localhost`)"
      - "traefik.http.routers.mshowto.entrypoints=web"